### ISSUE TITLE
for https://www.hoyolab.com/

### ISSUE THREAD

**Issue by cip300** [mcxiaoke/CarrotProjects#1]
How to make accept the https://www.hoyolab.com/ cookies , i can't manage to make it work. 
Please help.

**Comment by mcxiaoke** [comment]
modify api related url and arguments https://github.com/mcxiaoke/CarrotProjects/blob/master/GenshinLib/GenshinConst.cs

you can try this https://github.com/DGP-Studio/Snap.Genshin hoyolab is supported maybe

**Comment by cip300** [comment]
Thank you ! I apreciate you response.

**Comment by cip300** [comment]
I tried and tried , can't seams to make accept cookies , here is the api:
https://upload-os-bbs.hoyolab.com/
https://bbs-api-os.hoyolab.com/
https://abtest-api-data-sg.hoyoverse.com/
https://webstatic.hoyoverse.com/
https://log-upload-os.hoyoverse.com/

https://api-os-takumi.hoyoverse.com/
https://sg-hk4e-api.hoyoverse.com/common/apicdkey/api/webExchangeCdkey

**Comment by mcxiaoke** [comment]
@cip300  for you, here it's a working example: https://github.com/y1ndan/genshinhelper2/blob/main/genshinhelper/hoyolab.py

**Comment by mcxiaoke** [comment]
https://github.com/Xm798/Genshin-Dailynote-Helper.git
